version: '3'

services:
    web:
      build: ./nginx
      container_name: learn_nginx
      volumes:
        - ./www/php:/usr/share/nginx/html
      restart: unless-stopped
      ports:
        - "8082:80"
      environment:
        - NGINX_HOST=localhost
        - NGINX_PORT=80
    learn_mysql:
      build: ./mysql
      container_name: learn_mysql
      environment:
        MYSQL_ROOT_PASSWORD: masterkey
        MYSQL_DATABASE: learn_mysql
      ports:
        - "3282:3306"
      volumes:
        - learn-db:/var/lib/mysql
    apache:
      build: ./apache
      container_name: apache
      volumes:
        - ./www/php:/var/www/html
      ports:
        - "8084:80"
      environment:
        WEB_DOCUMENT_ROOT: /var/www/html/web
#        WEB_DOCUMENT_INDEX: index.php
        PHP_MEMORY_LIMIT: 1024M
        PHP_UPLOAD_MAX_FILESIZE: 512M
        PHP_POST_MAX_SIZE: 512M
        PHP_DISPLAY_ERRORS: 1
        php.xdebug.max_nesting_level: 500
        XDEBUG_CONFIG: "xdebug.mode=debug"
        XDEBUG_MODE: coverage
    memcached:
      image: 'memcached:alpine'
      ports:
        - '11211:11211'
    redis:
      image: 'redis:alpine'
      ports:
        - '6379:6379'
volumes:
  learn-db:
